### ISSUE TITLE
datePicker 有没有选择月份？

### ISSUE THREAD

**Issue by jianliulin** [weui/weui.js#1]
datePicker 有没有选择月份？ 很多地方都用到，尤其是查询历史资料

**Comment by BearJ** [comment]
谢谢，我们后期会实现这个优化

**Comment by sklthegoodman** [comment]
@jianliulin 你的意思是不会出现日选择列表，只有年和月的列表么。

**Comment by BearJ** [comment]
@jianliulin 如果是选择月份的，可以直接传个月份数组进去即可
