### ISSUE TITLE
表单验证非必填项验证问题

### ISSUE THREAD

**Issue by zouliang073** [weui/weui.js#102]
表单验证非必填项无法做到验证，目前要开启验证就必须要必填，请问现在怎么做够实现这个效果？
不添加required直接就不验证了，添加required就必须得填写， 如果能够不添加emptyTips属性可以启用非必填验证的话就非常棒了

**Comment by BearJ** [comment]
@zouliang073 是不是要么不填，要么填了就要符合格式？那你可以试试正则：/^$|.{4}/ 
其实就是先判断是否为空~

**Comment by zouliang073** [comment]
谢谢，知道如何做了

**Comment by zouliang073** [comment]
@BearJ 谢谢，知道如何做了

**Comment by zouliang073** [comment]
@BearJ 抱歉，这样做不行，还是会验证空值的，目前我只有不做必填的，单独去做验证了

**Comment by zouliang073** [comment]
@BearJ 我看了一下源码，https://github.com/weui/weui.js/blob/master/src/form/form.js
第53行的时候，
`else if(!$input.val().length){
            return 'empty';
        }`
直接就empty了，根本不给验证正则的机会

**Comment by BearJ** [comment]
@zouliang073 哦哦，抱歉，这个是develop分支上修复了的，下个版本带上哈~目前建议先不加required，然后等validatef返回成功之后再人工校验一下那个输入框

**Comment by gongxw** [comment]
@BearJ 其他表单验证应该有存在同样问题，比如CheckBox。在develop分支里35行，count等于0，直接返回'empty'了，没有经过正则'{0,2}'

**Comment by novawei** [comment]
master版本非必填项无法做到验证,绕个弯路,非必填的验证通过正则处理下
例如可选输入手机号的验证
`<input required pattern="REG_PHONEOPTIONAL">`
`regexp: {
    PHONEOPTIONAL: /^(1[0-9]{10})?$/
}`
