### ISSUE TITLE
checkbox 校验无法通过，浏览器要求 required 必选

### ISSUE THREAD

**Issue by fenbox** [weui/weui.js#109]
```
<input type="checkbox" name="assistance" value="黄药师" required pattern="{1,2}" tips="请勾选1-2个敲码助手" />
<input type="checkbox" name="assistance" value="欧阳锋" />
<input type="checkbox" name="assistance" value="段智兴" />
<input type="checkbox" name="assistance" value="洪七公" />
```

https://github.com/weui/weui.js/blob/master/docs/component/form.md
按示例中的代码，勾选 1、2 个即可，但是发现如果不勾选上面的”黄药师“，浏览器会阻止并要求勾选”黄药师“才行，怎么解决？

**Comment by BearJ** [comment]
@fenbox 是PC吗？还是手机端？手机端的话型号，微信版本可以报一下不？

**Comment by fenbox** [comment]
手机端的微信里，moto x 2014，刷了 LineageOS 14.1 (Android 7.1.2)
微信版本 6.5.7

**Comment by BearJ** [comment]
@fenbox 是否用了原生的form submit？如果是的话请在<form>处加上属性`novalidate`，比如：
```html
<form novalidate>
</form>
```

**Comment by fenbox** [comment]
确实是，加了 `novalidate` 后就没问题了
