### ISSUE TITLE
ionic的model中调用picker虽然正确的显示在了最上层但是操作的是picker后面的视图

### ISSUE THREAD

**Issue by gtUserName** [weui/weui.js#114]
# 使用场景：
`ionic`的`model`中调用`picker`，由于涉及到多个视图层相互影响（界面中多个嵌套的`postion: ababsolute;` `postion: fixed;` 如何影响没弄太懂）导致`picker`虽然正确的显示在了最前面，但是操作时操作的是picker后面的视图

# 解决办法：
看了一下picker的代码，下面的代码将picker append到body中
```js
$('body').append($picker);
```
经过测试如果将 `picker append` 到 `model` 中描述的问题就没有，通过下面的代码增加默认参数，使picker可以指定装载的容器
```js
@@ -166,6 +166,7 @@ function picker() {
     const options = arguments[arguments.length - 1];
     const defaults = $.extend({
         id: 'default',
+        container: 'body',
         className: '',
         onChange: $.noop,
         onConfirm: $.noop
@@ -194,7 +195,7 @@ function picker() {

    // 显示与隐藏的方法
    function show(){
-       $('body').append($picker);
+       $(defaults.container).append($picker);

        // 这里获取一下计算后的样式，强制触发渲染. fix IOS10下闪现的问题
        $.getStyle($picker[0], 'transform');
```
[commit记录](https://github.com/gtUserName/weui.js/commit/7dcef734ce1728f12a109374a7feb510d5162270)

**Comment by BearJ** [comment]
@gtUserName 谢谢建议，欢迎给我们pr~
