### ISSUE TITLE
Loading 组件建议增加一个全局关闭的 API

### ISSUE THREAD

**Issue by zaxlct** [weui/weui.js#118]
做单页面应用时有这个一个场景：用户进入到一个页面，此时启动 loding ，然后 ajax 请求数据，数据请求成功后，关闭 loding 。
但是用户在启动 loding 后，没等拿到数据就离开了该页面。因为是单页面应用，这个 loading 不会消失。
如果有一个全局关闭 loding 的 API 就好了。

**Comment by zaxlct** [comment]
抽空看看源码，看看自己能不能参与 PR 下，哈哈

**Comment by qichhhhh** [comment]
应该监听一下用户离开的动作调用loading.hide()  loading设为全局变量就行啦

**Comment by zaxlct** [comment]
@qichhhhh 多谢！
