### ISSUE TITLE
在ios中，自动上传方式时点击上传是直接进入拍照，无法选择图库，手动上传却可以选择，求指教。

### ISSUE THREAD

**Issue by zhaojianhui129** [weui/weui.js#119]
如题

**Comment by BearJ** [comment]
区别在这里：
![image](https://cloud.githubusercontent.com/assets/2395166/25663919/9a574604-304b-11e7-95eb-4eafca6eaf26.png)

**Comment by zhaojianhui129** [comment]
太感谢了，问题解决了。
