### ISSUE TITLE
同一picker多次调用时显示的是上次缓存的结果，没有办法设置新的值

### ISSUE THREAD

**Issue by gtUserName** [weui/weui.js#124]
### 问题描述：
在单页应用中碰到这个问题，在同一个视图中存在多次显示修改时间的需求，使用多列picker后发现同一个picker每次显示的是上次缓存的结果，修改defaultValue无法达到每次显示想要的结果，这种使用场景不知道官方的版本是否能够考虑支持。

### 修改方案 
看源码是在下面的地方处理了缓存，我使用了简单的不使用缓存的方式进行处理后本地编译了一个版本。
```js
    // 获取缓存
-    temp[defaults.id] = temp[defaults.id] || [];
+    temp[defaults.id] = [];
     const result = [];
     const lineTemp = temp[defaults.id];
     const $picker = $($.render(pickerTpl, defaults));
```
目前能够想到比较完善一点的修改方式是增加value属性，picker执行的时候判断如果有value属性的话，将
value赋值给defaultValue，同时将对应的缓存清空，其他情况保持不变。

**Comment by BearJ** [comment]
@gtUserName 可以参考#32

**Comment by gtUserName** [comment]
@BearJ 谢谢你
每次picker显示的时候都会重新构造dom这是我没有注意到的点，之前写代码的习惯是使用hide和show的方式处理组件的显示隐藏，留下了惯性思维

weui.js picker函数调用时都会重新构造DOM
```js
    // 获取缓存
    temp[defaults.id] = temp[defaults.id] || [];
    const result = [];
    const lineTemp = temp[defaults.id];
    // 构造DOM
    const $picker = $($.render(pickerTpl, defaults));
    let depth = options.depth || (isMulti ? items.length : util.depthOf(items[0])), groups = '';
```
picker hide时将缓存DOM元素remove了，同时将全局的引用删除释放内存
```js
                $picker.remove();
                _sington = false;
                callback && callback();
```
残留了temp中的内存没有释放，但这里只是缓存了一个value数组，基本上可以忽略对内存的影响。
