### ISSUE TITLE
如何删除选择的所有文件？

### ISSUE THREAD

**Issue by strongant** [weui/weui.js#14]

**Comment by progrape** [comment]
![image](https://cloud.githubusercontent.com/assets/4652816/21250429/1d582dc2-c380-11e6-85a0-1710a2388984.png)

![image](https://cloud.githubusercontent.com/assets/4652816/21250435/28aecb7c-c380-11e6-92c9-ecd642414966.png)

@strongant 你好，可以点击缩略图查看大图，然后在底部删除

**Comment by strongant** [comment]
我不是这个意思，我意思如果我上传了三张图片，用户取消上传后删除已经上传的所有图片

**Comment by BearJ** [comment]
@scotthuang 这个需要后台提供个接口给你调用才能删掉后台的图片

**Comment by strongant** [comment]
嗯，谢谢搞定了.
