### ISSUE TITLE
微信扫码打开页面后如何关闭窗口？js原生的window.close()方法不执行？

### ISSUE THREAD

**Issue by strongant** [weui/weui.js#16]

**Comment by progrape** [comment]
可以用 jssdk 的方法 `wx.closeWindow()`

**Comment by strongant** [comment]
jssdk  是不是需要引入才可以使用？

**Comment by progrape** [comment]
是的，使用方式详见 https://mp.weixin.qq.com/wiki 微信网页开发——微信JS-SDK说明文档

**Comment by strongant** [comment]
麻烦问一下其它功能不需要，就单独的关闭页面操作，不使用微信JS-SDK操作，常规方法是不生效的？

**Comment by progrape** [comment]
常规的 `windows.close()` 估计不生效，但是可以试试 `WeixinJSBridge.invoke('closeWindow');` 。在微信内有 `WeixinJSBridge` 对象，closeWindow 好像不用签名鉴权

**Comment by strongant** [comment]
谢谢你，刚才试了一下是可以的。:gift_heart:

**Comment by progrape** [comment]
不客气~

**Comment by wangfpp** [comment]
IOS不生效 有什么办法可以解决吗
