### ISSUE TITLE
十分赞，可否发布一个公共cdn，就像weui一样？

### ISSUE THREAD

**Issue by zzzeep** [weui/weui.js#17]
`<link href="//res.wx.qq.com/open/libs/weui/1.1.0/weui.min.css" rel="stylesheet">`

**Comment by zzzeep** [comment]
谢谢

**Comment by progrape** [comment]
@zzzeep 你好，CDN 地址是一下两个：
https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.js
https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.min.js

**Comment by zzzeep** [comment]
@progrape 十分感谢！

**Comment by larryli** [comment]
怎么没在 README.md 文档里面。

**Comment by BearJ** [comment]
@larryli 我们更倾向于写在wiki里 ^_^

**Comment by larryli** [comment]
@BearJ README.md 有 docs 的入口，但是没有 wiki 的入口。
https://github.com/weui/weui 项目文档直接在 wiki，README.md 也有入口，比较好找。

另外，最好还是在每个 release 也给出对应版本的 url。

**Comment by BearJ** [comment]
@larryli weuijs的docs是根据代码的注释而生成的，所以weui没有而这里有。不过你说得对，我在README.md里面的加个入口吧。release已经改了，谢谢你的建议 ^_^
