### ISSUE TITLE
图片上传组件，手动上传，预览图出不来

### ISSUE THREAD

**Issue by gtyd** [weui/weui.js#19]
图片上传组件，手动上传，点击预览图，只有一个黑色的界面，下面有删除，无法加载图片
环境：chrome

**Comment by gtyd** [comment]
已解决，用chrome模拟的无法预览，生成二维码用微信打开是可以的

**Comment by fairyly** [comment]
这个问题依然存在啊，以前解决了手机端可以预览，更新后出问题了

**Comment by BearJ** [comment]
@fairyly 请问是啥问题？预览图出不来吗？

**Comment by fairyly** [comment]
@BearJ 感谢啊，看到了更新的版本已经解决了
