### ISSUE TITLE
支持小程序吗？

### ISSUE THREAD

**Issue by cocoli** [weui/weui.js#2]
能否在小程序调用呢？

**Comment by progrape** [comment]
你好，这个是操作 DOM 的，用在网页，小程序运行的 app service环境没有 DOM，不能使用。

另外，小程序提供的组件都包含了 js 调用方式的，不需要额外封装 js 功能。

**Comment by cocoli** [comment]
这几天不停的收到有公众号和qq群转发发布小程序视觉组件weui.js 的文章，请问weui.js支持小程序是否属实？或未来支持。

**Comment by sklthegoodman** [comment]
weui.js的场景是网页不是小程序，所以是不支持小程序的。

**Comment by sklthegoodman** [comment]
weui.js的场景是网页不是小程序，所以是不支持小程序的。
小程序是默认有逻辑封装的，并不需要引入额外的JS
@cocoli

**Comment by cocoli** [comment]
谢谢回复，有些媒体见风就是雨，带来很大的误导性。
