### ISSUE TITLE
Picker为什么result只返回value，而不返回label？

### ISSUE THREAD

**Issue by Mavis-0211** [weui/weui.js#20]
在表单中需要填入label值，提交表单时需要提交value值。目前result只返回了value值，请问使用者们怎么把label值填入表单页面显示出来的......
不返回一个对象，只返回value，是出于什么特殊的考虑吗？

**Comment by sklthegoodman** [comment]
当时是考虑到尽量让result结构简单一些，所以label只作为展示而不作返回值。
因为现在label和value都是可以自己定制，你可以考虑先将value直接定义成你想要的样子。

我们讨论一下返回label是否必要。

**Comment by quzhilin** [comment]
还好

**Comment by baiyapeng** [comment]
确实，我现在只能把`value + '-' + label`整体作为`value`再自己截取

**Comment by BearJ** [comment]
现在v1.1.0 picker将同时返回label和value了
