### ISSUE TITLE
upload控件，拍照预览图倒转了90°

### ISSUE THREAD

**Issue by gtyd** [weui/weui.js#22]
如题，环境：iPhone6s、iOS10.2
拍照后使用图片是反的

**Comment by BearJ** [comment]
@gtyd 谢谢提醒，这个后期需要fix

**Comment by gtyd** [comment]
@BearJ 
在Android环境下，小米、华为都只能选择图片，没有拍照选项。魅族、iPhone没问题
经测试，需在input标签上加capture属性才可以
`<input id=uploaderCustomInput class=weui-uploader__input type="file" accept="image/*" capture="camera" multiple="">`

**Comment by BearJ** [comment]
@gtyd 倒转的问题在develop分支上以修复，你可以单独下载下来试试？

**Comment by gtyd** [comment]
@BearJ 重新引用了develop分支dist目录下的weui.js，拍照完点使用图片，还是被旋转了哇！

**Comment by BearJ** [comment]
@gtyd 方便提供下设备信息，系统信息，和微信版本吗？

**Comment by lewis121** [comment]
develop分支下的weui.js在iphone5S下测试正常了。

**Comment by luqin** [comment]
`capture="camera"` 在华为安卓浏览器中可以拍照，但是微信内置浏览器中依然无法拍照。

**Comment by gtyd** [comment]
@BearJ 已查明原因，在压缩模式下是ok的，不启用压缩还是会旋转，嘿嘿
`if (options.compress === false) {
                            // 不启用压缩 & base64上传 的分支，不做任何处理，直接返回文件的base64编码
                            file.base64 = evt.target.result;
                            callback(file);
                            return;
                        }

                        // 启用压缩的分支
                        var img = new Image();
                        img.onload = function() {
                            var ratio = detectVerticalSquash(img);
                            var orientation = getOrientation(dataURItoBuffer(img.src));
                            alert(orientation);`

**Comment by gtyd** [comment]
@BearJ 已查明，当不启用压缩，拍照后依然是被旋转了，控制翻转的代码只写在了“启用压缩的分支”块内，见：
`
if (options.compress === false) 
{
    // 不启用压缩 & base64上传 的分支，不做任何处理，直接返回文件的base64编码
   file.base64 = evt.target.result;
   callback(file);
   return;
}
`

**Comment by BearJ** [comment]
@gtyd 是的呢，不做任何处理是因为有些需求是要保留图片信息，所以也就没有做调整

**Comment by gtyd** [comment]
@BearJ 如果我想保持原图，不启用压缩（不需要保留图片信息），但要解决旋转，可否单独给一个版本？谢谢

**Comment by BearJ** [comment]
@gtyd 是想保留原图的尺寸吗？那你试试这样设置compress，就算我提供一个新版本，实现原理也是一样的：
```javascript
compress: {
       width: 99999,
       height: 99999,
       quality: 1
   }
```

**Comment by gtyd** [comment]
@BearJ 可以解决，感谢！

**Comment by gtyd** [comment]
@BearJ 有没有每次发布版本后的更新说明呢？

**Comment by BearJ** [comment]
@gtyd 有的，https://github.com/weui/weui.js/releases

**Comment by BearJ** [comment]
这里v1.1.1 fixed

**Comment by hangpage** [comment]
compress: {
    width: 99999,
    height: 99999,
    quality: 1
} 您好，这段代码需要粘在哪里呢，现在用了1.1.1ios还是照片旋转了90° @BearJ
