### ISSUE TITLE
datePicker月份为何比选择的小一个月？

### ISSUE THREAD

**Issue by allan2coder** [weui/weui.js#24]
datePicker月份为何比选择的小一个月？

**Comment by BearJ** [comment]
@allan2coder 请问使用的是最新版吗？这个是已经fix了: https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.min.js

**Comment by allan2coder** [comment]
@BearJ 我用的是最新版的。依旧有这个bug！

**Comment by progrape** [comment]
@allan2coder 示例里面已经是正确了的 https://weui.io/weui.js/
![image](https://cloud.githubusercontent.com/assets/4652816/21474863/fcbff166-cb5f-11e6-886e-8dd0477a4953.png)

**Comment by allan2coder** [comment]
好的。
