### ISSUE TITLE
datePicker格式有选择吗？不想要这种[YYYY,MM,DD]数组、想要YYYY-MM-DD

### ISSUE THREAD

**Issue by allan2coder** [weui/weui.js#25]
datePicker格式有选择吗？不想要这种YYYY,MM,DD、想要YYYY-MM-DD
 
文档也没有，真是醉了。

**Comment by BearJ** [comment]
@allan2coder 文档在wiki那里：https://github.com/weui/weui.js/wiki
看是否满足你的需求？

**Comment by allan2coder** [comment]
@BearJ 恩、找到了。

年月日应该是需要自己拼的是吧？

**Comment by BearJ** [comment]
@allan2coder 是的
