### ISSUE TITLE
关于 alert confirm dialog中的按钮

### ISSUE THREAD

**Issue by qq71151461** [weui/weui.js#27]
里面的按钮回调方法里，能不能接受return false ,不要关闭窗口内容.
因为特殊情况下,比如我dialog里放了form表单内容,点按钮时,需要表单检验,检验成功后,才关闭窗口!!

**Comment by qq71151461** [comment]
或再内置一方法,可以手动关闭当前弹窗.

**Comment by BearJ** [comment]
@qq71151461 这样子~那我们内部讨论一下

**Comment by BearJ** [comment]
现在v1.1.0 支持了
