### ISSUE TITLE
loading在定位元素上显示不出来

### ISSUE THREAD

**Issue by ydq** [weui/weui.js#28]
当页面元素本身是定位元素，且有zIndex时，loading界面显示不出来
![image](https://cloud.githubusercontent.com/assets/8097340/21445824/203b3be6-c8f9-11e6-93d2-983523c79b9b.png)
如上图：
当前这个表单页面是定位元素，有zIndex属性，导致loading被遮挡出不来，因为loading最外层的容器不是定位元素，没有zIndex属性
![image](https://cloud.githubusercontent.com/assets/8097340/21445832/436b5b3c-c8f9-11e6-94de-4fd9c9f58bd2.png)
经过测试，将loading的容器，设置成定位（relative，absolute，fixed都可以），然后给zIndex一个比较大的值，就可以正常显示了，虽然我觉得这个应该反馈在weui里面

**Comment by BearJ** [comment]
@ydq 谢谢哈，这个我们会在下个版本做修复~

**Comment by BearJ** [comment]
现在v1.1.0 修复了
