### ISSUE TITLE
datepicker  不支持PC微信浏览器呢？

### ISSUE THREAD

**Issue by docikaci** [weui/weui.js#29]
picker  滑动选择 都不支持？ 有打算支持吗？
谢谢

**Comment by BearJ** [comment]
@docikaci 你好，这个我们先讨论一下哈~

**Comment by docikaci** [comment]
hi 我是北京这边的同事，有打算支持吗？哪怕是降级，功能能用也行呀，如果有近期打算支持的话，我们就不用再写PC上的一套了，
谢谢

**Comment by BearJ** [comment]
@docikaci 你好，develop上已经支持了，可以直接使用~https://github.com/weui/weui.js/blob/develop/dist/weui.min.js

**Comment by docikaci** [comment]
我 try 一下  多谢

**Comment by BearJ** [comment]
现在v1.1.0 支持了
