### ISSUE TITLE
能否增加单页面路由的功能

### ISSUE THREAD

**Issue by grg-ligang** [weui/weui.js#3]
开发公众号涉及到用户信息的获取与腾讯的授权 ，多个HTML文件跳转比较麻烦。 能否写一个单页面路由，简单的几个页面都在一个HTML完成。

**Comment by BearJ** [comment]
@grg-ligang github有很多路由库，我们就不重复造轮子了

**Comment by oqy** [comment]
@BearJ 您好，能推荐一些路由库吗？谢谢

**Comment by BearJ** [comment]
https://github.com/tildeio/router.js/
