### ISSUE TITLE
datepicker是否可以添加配置开启当前时间以前的不能选择限制

### ISSUE THREAD

**Issue by lrwbaron** [weui/weui.js#30]
datepicker是否可以添加配置开启当前时间以前的不能选择限制。

**Comment by progrape** [comment]
这个有需求，我们考虑做得更加通用一些，不仅仅是当前以前时间

**Comment by mablevi** [comment]
@progrape 请抓紧开发这个需求。

**Comment by progrape** [comment]
@mablevi 大体开发完毕，在进行功能测试和性能测试

**Comment by progrape** [comment]
https://github.com/weui/weui.js/blob/develop/docs/component/picker.md#datepickeroptions

**Comment by BearJ** [comment]
现在v1.1.0 支持cron了
