### ISSUE TITLE
datapicker默认显示的时间和默认时间为当前初始时间的defaultValue: [date.getFullYear()],失效

### ISSUE THREAD

**Issue by LazyHua** [weui/weui.js#33]
把文件发布出去，在微信和UC浏览器上，不支持datapicker，只出现灰色背景没有白色的时间选择器，不报错，找了很久，终于可以正常显示，但是之前设置的默认时间为当前初始时间的defaultValue: [date.getFullYear()],这个失效了，显示的时间是2015年的时间，请问这是为什么

**Comment by BearJ** [comment]
@LazyHua 请问你发现是什么原因导致不正常显示的？至于defaultValue，你是这样写的吗？我试过OK
![image](https://cloud.githubusercontent.com/assets/2395166/21585904/52a3f8bc-d104-11e6-9554-0cf5fffb17a0.png)

**Comment by LazyHua** [comment]
就是你这样写的，我找到了原因了，好像是weui.min.js的版本问题导致的，我试着换了个版本就可以正常显示了，不懂为啥

**Comment by BearJ** [comment]
@LazyHua 是的，defaultValue是新的属性，老版本是没有的，建议你使用最新版：https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.min.js
