### ISSUE TITLE
上传图片后预览在浏览器模拟时候有点问题

### ISSUE THREAD

**Issue by fairyly** [weui/weui.js#35]
主要是background-image:的url有点问题，手机端测试没问题可以显示；
这是浏览器模拟的数据：<span class="weui-gallery__img" style="background-image:url(" blob:http:="" localhost="" e129602c-3cf5-42ca-b6fa-cbe0b7730090")"="">"blob:http://localhost/e129602c-3cf5-42ca-b6fa-cbe0b7730090"</span>

**Comment by BearJ** [comment]
嗯嗯，这个我们在看了~

**Comment by fairyly** [comment]
@BearJ 恩恩好的，整体用着感觉还不错的，实际开发中预览删除的时候总是删除数组中第一个数据，不知道是我本地的问题啊还是插件的问题，实际开发中我已经改写了，感谢ing

**Comment by BearJ** [comment]
@fairyly 你是指删除哪里有问题？

**Comment by BearJ** [comment]
@fairyly 现在v1.1.0 修复了

**Comment by fairyly** [comment]
@BearJ 是预览的问题修复吗

**Comment by BearJ** [comment]
嗯嗯，是的，PC预览的问题
