### ISSUE TITLE
gallery 组件不显示问题

### ISSUE THREAD

**Issue by baiyapeng** [weui/weui.js#37]
问题极其怪异，是这样子的，一样的代码在安卓所有版本的微信客户端是没有问题的，图片可以正常显示。但是在某些 iPhone 机上是有问题的，首先是 iPhone5 Plus 上**没有问题**（犹如安卓机一样流畅），但是在iPhone6 Plus、iPhone7 上**有些图片**会显示不出来（比如两组图片，A组都可以而B组统一都显示不出来。是的，好像这些客户端商量好的一样对这组图片屏蔽了一样），百思不得其解，特来求助，没有代码（需要的话周一我传一下），希望给个方向性建议~

**Comment by baiyapeng** [comment]
另外，在微信开发者工具中都是没有问题的~

**Comment by BearJ** [comment]
是小程序吗？

**Comment by ps2qwert** [comment]
`url = url.match(/url\((.*?)\)/)[1];
""blob:https%3A//weui.io/375b050e-f645-4b12-90df-c9e43b8b7a84""`
提取图片链接后显示两个对双引号，去掉一对后，gallery图片显示正常

**Comment by BearJ** [comment]
@ps2qwert 是的，develop分支已fixed

**Comment by BearJ** [comment]
@ps2qwert 现在v1.1.0 修复了

**Comment by baiyapeng** [comment]
@BearJ 好的，多谢通知
