### ISSUE TITLE
在使用weui.form.validate进行表单验证的时候不停提示请与所请求的格式保持一致。

### ISSUE THREAD

**Issue by TroyIrvo** [weui/weui.js#40]
![image](https://cloud.githubusercontent.com/assets/19662959/21974386/6ec82880-dc01-11e6-9ac2-3ed7b6c1bc29.png)

**Comment by waitingmyself** [comment]
请问这个问题是怎么解决的？  html5的pattern属性与weui里面的校验冲突了。
