### ISSUE TITLE
使用Vue.js框架后，form表单验证无法工作

### ISSUE THREAD

**Issue by atawat** [weui/weui.js#41]
在使用vue之后，其渲染出来的input元素会给required属性添加一个“required”的value，类似这样
`<input data-v-d26d3a4a="" name="ContactName" required="required" type="text" placeholder="请输入联系人名称" class="weui-input">`，在默认情况下，表单的验证就无法工作。
经检查是 `function _validate($input,$form,regexp)` 下的 `var reg = input.getAttribute('required') || input.getAttribute('pattern') || '';` 此句获取的reg值为“required”，导致后面的逻辑都将验证字符串是否匹配"requied"，所以给出错误的验证结果，希望官方能改进此处以适应vue.js

**Comment by BearJ** [comment]
@atawat 谢谢，下个版本修复这问题

**Comment by BearJ** [comment]
@atawat 现在v1.1.0 把`input.getAttribute('required')`干掉了
