### ISSUE TITLE
actionSheet的hide方法在某些情况下会报错

### ISSUE THREAD

**Issue by yikuo123** [weui/weui.js#42]
如果在actionSheet的menu回调方法中手动调用了hide方法关闭actionSheet，回调结束后actionSheet仍然会尝试关闭一次，这时候就会报错。

使用场景是这样的：
正常情况下点击actionSheet中的menu后，actionSheet会自动关闭。
但是，单页应用中，如果在actionSheet打开的情况下返回上一个页面，就必须手动关闭actionSheet。因此，我必须要在切换页面时手动调用actionSheet的hide方法。然后呢，我有一个menu会触发页面切换，这时候actionSheet是打开的，页面切换调用了一次hide，actionSheet自动关闭又调用一次，就出现了前面描述的问题。

建议调用hide方法的时候判断一下actionSheet是不是还存在。

**Comment by BearJ** [comment]
@yikuo123 明白了，谢谢~下个版本修复
