### ISSUE TITLE
picker的defaultValue无效？

### ISSUE THREAD

**Issue by yangkai314** [weui/weui.js#43]
picker的defaultValue设置了不起作用啊，就按官网的例子加了一个defaultValue

**Comment by BearJ** [comment]
@yangkai314 请问你使用的是最新的代码吗？https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.min.js
如果defaultValue不在内容数组内，也是会不生效的。

**Comment by xdrblog** [comment]
defaultValue是不生效的，压缩代码里面没有defaultValue相关的逻辑处理
