### ISSUE TITLE
表单验证可以单独验证吗，比如说绑定里面的input，可以单独验证input。

### ISSUE THREAD

**Issue by bigzs** [weui/weui.js#46]
就是一个简单的短信注册功能，手机号跟验证码这两个文本框可以用表单验证，然后获取验证码的时候，单独验证手机号，这个有单独的用法吗？

**Comment by BearJ** [comment]
@bigzs 在获取验证码的时候手动校验一下手机的那个输入框？

**Comment by bigzs** [comment]
是的。

**Comment by BearJ** [comment]
@bigzs 可以传入input的父层的selector，然后用weui.form.validate
