### ISSUE TITLE
不能同时打开多个dialog窗口

### ISSUE THREAD

**Issue by qichhhhh** [weui/weui.js#47]
场景：
用户点击某提交按钮，弹出confirm窗口。用户确认信息后点击【确认】按钮，此时执行【确认】按钮的回调事件，同时confirm执行hide()方法。 如果回调事件内要弹出alert窗口，但是此时confirm窗口的hide()还未执行完毕，所以导致alert无法弹出

1.建议在hide()方法添加一个回调事件的传参，可以在hide()完成后执行。
2.或者只允许 alert/confirm/dialog 同时只存在一个。（即允许同时存在一个alert，一个aconfirm，一个dialog。但是不允许同时存在两个alert。）

**Comment by BearJ** [comment]
这里倾向于第一种方案，下个小版本优化

**Comment by BearJ** [comment]
这里v1.1.1 优化了
