### ISSUE TITLE
toast 的时间 duration 失效

### ISSUE THREAD

**Issue by bigzs** [weui/weui.js#48]
window.location.replace('xxxx');
window.event.returnValue = false;
这两行放到toast前面，toast的时间就失效了。直接就执行回调了。
这两行放到toast回调里面，这两行就失效了。这两行是用来抑制后退的。
![qq 20170213173717](https://cloud.githubusercontent.com/assets/25221782/22878052/21ce78ae-f213-11e6-8f46-151707691aa1.png)

**Comment by BearJ** [comment]
@bigzs 你把前面的那两行换成alert(1)  callback里的那两行换成alert(2)。你就知道为啥了？duration其实没有失效，是因为你代码让页面跳转了
