### ISSUE TITLE
1.1版本  picker组件 点击时会移动2倍的距离

### ISSUE THREAD

**Issue by julyL** [weui/weui.js#49]
地址： https://jsfiddle.net/qinmi258/zzaaensv/1/
把代码放本地，用chrome手机模式测试
 weui.js1.0版本没有问题   
weui.js 1.1 版本  有如下bug  
![image](https://cloud.githubusercontent.com/assets/12106591/22878173/ab1f3cec-f213-11e6-9042-a648f8fd3e35.png)
点击B2会直接跳C3
点击C3会直接跳E5
会移动2倍的距离

(小米4手机测试)

**Comment by BearJ** [comment]
@julyL 你用你那台手机打开demo试试看有没有问题？https://weui.io/weui.js/

**Comment by julyL** [comment]
https://weui.io/weui.js/ 的demo 小米4手机测试距离会移动2倍，但chrome手机模拟正常。
下图为weui1.1版本测试情况    https://res.wx.qq.com/open/libs/weuijs/1.1.0/weui.min.js  
chrome下测试的情况，手机上一样有问题，会移动2倍距离。
![1](https://cloud.githubusercontent.com/assets/12106591/22922839/2d5d110e-f2da-11e6-991b-bf58bb279abb.gif)
改为https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.min.js    则正常

**Comment by julyL** [comment]
https://weui.io/weui.js/ 的demo 小米4手机测试距离会移动2倍，但chrome手机模拟正常。

下图为我本地引用weui1.1版本测试情况    https://res.wx.qq.com/open/libs/weuijs/1.1.0/weui.min.js  
chrome下测试的情况，手机上一样有问题，会移动2倍距离。
![3](https://cloud.githubusercontent.com/assets/12106591/22923045/dd5086fe-f2da-11e6-8088-aee1a052c20a.gif)
改用weui1.0   https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.min.js    则正常

**Comment by BearJ** [comment]
好的，谢谢哈~我来看看~

**Comment by BearJ** [comment]
@julyL 在develop上已经fix了，你下载来试试看？

**Comment by BearJ** [comment]
这里v1.1.1 fixed
