### ISSUE TITLE
gallery 没有左右滑动功能？

### ISSUE THREAD

**Issue by pkkgu** [weui/weui.js#50]
gallery 没有左右滑动功能？

**Comment by BearJ** [comment]
@pkkgu 没有的，但有两种方案：一种是用jsAPI，一种是用第三方的库做swiper

**Comment by pkkgu** [comment]
目前使用JSAPI，但是没有删除按钮不方便。

**Comment by BearJ** [comment]
@pkkgu 用JSAPI是最流畅的，毕竟原生。如果是删除的话，可以尝试在页面上传缩略图的右上角加个大概30*30的删除按钮。

**Comment by wuchao288** [comment]
有加上左右滑动功能的开发计划吗？可以加入这功能的话这个就更完善了。

**Comment by BearJ** [comment]
@wuchao288 网上有很多挺好的库的，这里就没必要重复造轮子了。比如说bootstrap的unslider:
http://www.bootcss.com/p/unslider/

**Comment by rockan007** [comment]
jsAPI 是啥？

**Comment by Frank-MJ** [comment]
@pkkgu 你说的JSAPI是什么，可以具体说一下嘛

**Comment by qinghechaoge** [comment]
@Frank-MJ @rockan007 可以用 [http://photoswipe.com/](url)

**Comment by Frank-MJ** [comment]
@qinghechaoge 你使用这个插件解决了weui里面的gallery没有左右滑动的功能吗？？
