### ISSUE TITLE
gallery模板中的url

### ISSUE THREAD

**Issue by 993318936** [weui/weui.js#53]
此处的url可以选择不插入吗？在微信里打开顶上还有一层微信app的导航占去了一定高度，当预览图是一些高度比较大的图例如截屏时很影响美观，顶上会有一排url
[https://github.com/weui/weui.js/blob/master/src/gallery/gallery.html](url)
`<span class="weui-gallery__img" style="background-image: url(<%= url %>);"><%= url %></span>`

**Comment by BearJ** [comment]
@993318936 是的，这是bug，下个版本fix~

**Comment by 993318936** [comment]
@BearJ  好的 感谢您抽空回复

**Comment by BearJ** [comment]
这个v1.1.1 fixed
