### ISSUE TITLE
alert,confirm,dialog,toast 可以增加 显示后和隐藏（CSS过度完成）的事件吗？

### ISSUE THREAD

**Issue by pkkgu** [weui/weui.js#55]
alert,confirm,dialog,toast 可以增加 显示后和隐藏后（CSS过度完成）的事件吗？

例如Bootstrap 模态框事件
http://v3.bootcss.com/javascript/#modals-events

**Comment by BearJ** [comment]
@pkkgu 显示的话目前还没有，但是隐藏后的下个版本会提供，将在hide里面有个回调函数。可以看这个issue： #47
