### ISSUE TITLE
为TopTips添加成功样式primary以及警告样式warning

### ISSUE THREAD

**Issue by haosijiahsj** [weui/weui.js#57]
在TopTips中是不是仅仅只有错误样式红色？希望后续能够添加其它颜色样式，或者给一个参数让用户自己传入颜色

**Comment by BearJ** [comment]
@haosijiahsj 可以传入一个自定义类名，然后你通过类名来控制颜色即可~
![image](https://cloud.githubusercontent.com/assets/2395166/23248227/4217c19c-f9d9-11e6-9e94-f1a2bec43e3b.png)

**Comment by haosijiahsj** [comment]
明白了  谢谢咯

**Comment by haosijiahsj** [comment]
@BearJ 明白了  谢谢咯
