### ISSUE TITLE
picker联动显示问题

### ISSUE THREAD

**Issue by jiechina** [weui/weui.js#60]
http://jsbin.com/dopotenike/edit?html,js,output
示例如上，请问在做省市区联动的时候，picker数据可以正确获取 但是显示不正确（不能显示第三级） 是怎么回事，换成官方示例数据又可以正确显示

**Comment by BearJ** [comment]
@jiechina 我用 [codepen](http://codepen.io/bearyan/pen/WpvoQM) 可以，怀疑是jsbin对样式做了修改~

**Comment by jiechina** [comment]
@BearJ   看了你的  显示的实际上还是只有省市2级 不能显示第三级区县

**Comment by BearJ** [comment]
@jiechina 抱歉，理解错问题哈。。那你只要加上depth:3即可

**Comment by jiechina** [comment]
@BearJ  感谢了  原来是没仔细看参数说明
