### ISSUE TITLE
weui弹窗无法嵌套使用

### ISSUE THREAD

**Issue by tianyu8969** [weui/weui.js#61]
弹窗无法被嵌套的使用，如下：无法弹出weui.alert
weui.dialog({
    title: 'dialog标题',
    content: 'dialog内容',
    className: 'custom-classname',
    buttons: [{
        label: '取消',
        type: 'default',
        onClick: function () {weui.alert("'取消"); }
    }, {
        label: '确定',
        type: 'primary',
        onClick: function () { weui.alert('确定') }
    }]
});

**Comment by BearJ** [comment]
@tianyu8969 用最新版试试？https://res.wx.qq.com/open/libs/weuijs/1.1.1/weui.min.js

**Comment by tianyu8969** [comment]
@BearJ 依旧不行，无法弹出嵌套的弹窗

**Comment by BearJ** [comment]
@tianyu8969 我在weui.io上试了下，没有问题哦~你那边有没有报错什么的？

**Comment by BearJ** [comment]
@tianyu8969 试试这样？

**Comment by tianyu8969** [comment]
@BearJ 这是可以的，谢谢解答。

**Comment by fengqiming** [comment]
@BearJ 谢谢

**Comment by fengqiming** [comment]
@BearJ 有个问题，就是var dialog = weui.dialog嵌套var dialog = weui.dialog的时候会无效
