### ISSUE TITLE
Bower version need upgrade

### ISSUE THREAD

**Issue by WhatAKitty** [weui/weui.js#62]
bower 上 版本不知道能否更新下，今天通过bower下载了，然后发现版本不对。

**Comment by BearJ** [comment]
@WhatAKitty 奇怪，这里没法bower呀...只有weui.css那里才有

**Comment by WhatAKitty** [comment]
@BearJ 因为涉及到打包问题，我现在在bower.json里用的是github地址。

**Comment by BearJ** [comment]
@WhatAKitty 那如果用的是github的话，那应该是最新版哒...

**Comment by WhatAKitty** [comment]
@BearJ 什么时候会上传bower啊？还是以后都不会有啊？bower现在也有weui.js，不过是其他人写的版本。

**Comment by BearJ** [comment]
@WhatAKitty 我叫那个占坑的人解决一下 >_<

**Comment by WhatAKitty** [comment]
@BearJ OK，谢谢！

**Comment by progrape** [comment]
![image](https://cloud.githubusercontent.com/assets/4652816/24090890/17041370-0d7f-11e7-9ec6-dd3ab9ba16f1.png)

@WhatAKitty hello，bower 的指向已经改过来了，`bower cache clean` 清理一下换成之后再试试看

**Comment by WhatAKitty** [comment]
@progrape 好的，thank you!
