### ISSUE TITLE
loading隐藏后，再loading无法显示

### ISSUE THREAD

**Issue by hcw2175** [weui/weui.js#63]
版本：1.1.0
Bug：ajax请求封装了ajaxLoading显示隐藏，请求前显示ajaxLoading，请求结束后隐藏ajaxLoading。在请求完毕后回调业务方法内再也无法显示_loading。

代码参考：

```javascript
// ajax内的ajaxLoading
var ajaxLoading = weui.loading("加载中...");
setTimeout(function () {
       // 请求结束隐藏loading
       ajaxLoading.hide();      

    // 请求回调再显示另外的secondLoading
    // _loading 无法再显示
      var _loading = weui.loading("加载中2...");      
  }, 2000);
```

**Comment by hcw2175** [comment]
发现loading.hide();有个延迟效果，应该是消失动画。

所以上面问题应该是因为这个延迟效果造成的，在loading未完全消失情况下再显示loading就不能显示了。

临时解决办法就是在回调设置下settimeout：

// ajax内的ajaxLoading
var ajaxLoading = weui.loading("加载中...");
setTimeout(function () {
       // 请求结束隐藏loading
       ajaxLoading.hide();      

    // 请求回调再显示另外的secondLoading
    // _loading 无法再显示
    setTimeout(function () {
        var _loading = weui.loading("加载中2...");      
    }, 2000);
  }, 2000);

**Comment by hcw2175** [comment]
另外关于loading有个建议：**现在loading后必须要赋值给变量，然后再通过变量来调用hide()方法。这样实在麻烦及了，能不能把这个变量隐藏到weui内部去，隐藏的时候只需要调用weui.loading.hide()就好了。**

**Comment by BearJ** [comment]
@hcw2175 v1.1.1版本的hide提供了回调的接口，你可以这样写：
```javascript
// ajax内的ajaxLoading
var ajaxLoading = weui.loading("加载中...");
setTimeout(function () {
    // 请求结束隐藏loading
    ajaxLoading.hide(function () {
        weui.loading("加载中2...");
    });
}, 2000);
```
至于你说的`weui.loading.hide()`调用的建议，的确可以考虑，谢谢~~

**Comment by hcw2175** [comment]
@BearJ  我知道有个回调。但实际情况下，ajaxLoading是封装在ajax.js中的，只作用于ajax请求前和请求结束的。

回调函数中是不会也不可能再使用ajaxLoading了。

**Comment by BearJ** [comment]
@hcw2175 那封装的话应该是有一个回调函数吧，那回调函数就可以写在hide里面呀，例如：
```javascript
ajaxLoading.hide(function () {
    callback(); // 外部的回调
});
```

**Comment by inteai** [comment]
weui.min.js:6 Uncaught TypeError: t is not a function
    at HTMLDivElement.<anonymous> (weui.min.js:6)
    at HTMLDivElement.<anonymous> (weui.min.js:6)

		function o() {
			function e(t) {
				e = r.
			default.noop, u.addClass("weui-animate-fade-out"), a.addClass("weui-animate-fade-out").on("animationend webkitAnimationEnd", function() {
					**o.remove(), s = !1, t && t()**
				})
			}
