### ISSUE TITLE
city-picker.js如何使用

### ISSUE THREAD

**Issue by yzp0112** [weui/weui.js#67]
![qq 20170303184054](https://cloud.githubusercontent.com/assets/19768750/23548139/10a9bafc-0041-11e7-957c-81cf09142d25.png)

使用city-picker.js怎样设置初始值？

**Comment by BearJ** [comment]
@yzp0112 我们没有提供city-picker.js的文件呀...这是weui.picker的用法：https://github.com/weui/weui.js/blob/master/docs/component/picker.md

**Comment by yzp0112** [comment]
不好意思写错了是picker-city.js

**Comment by yzp0112** [comment]
不好意思写错了是picker-city.js
