### ISSUE TITLE
actionSheet弹出后立刻消失

### ISSUE THREAD

**Issue by yikuo123** [weui/weui.js#68]
我在使用actionSheet（weui.js 所有版本，包括最新的1.1.1）的时候碰到一个很诡异的问题，只在某些iPhone型号中出现，不知道是我用得不对还是ios的bug，又或者是weui.js的bug。

我的用法是这样的：

``` javascript
    //禁止选中文字
    document.documentElement.style.webkitTouchCallout = "none";
    document.documentElement.style.webkitUserSelect = "none";
```
然后给一个div绑定taphold事件触发弹出actionSheet，同时给这个div绑定了一个click（换成tap试过，结果一样）事件。
```javascript
    $(".test")
    .on("taphold", function () {
        weui.actionSheet(
            [
                {
                    label: '1111',
                    onClick: $.noop
                },
                {
                    label: '2222',
                    onClick: $.noop
                }
            ]
        );
        return false;
    })
    .on("click", function () {
        $(this).toggleClass("sss");
    });
```

现象：
    actionSheet正常弹出，手松开时就自动消失了

奇怪的是，试过很多安卓手机，并没有这个问题。但有的iPhone会出现这个问题，有的iPhone却没有。
最让我不解的是，一台iPhone 6 、一台iPhone 6s、一台iPhone 5s，三台系统版本号完全一样，微信版本号也完全一样，6和6s正常，5s有问题，safari也有这问题，排除微信了的原因

我尝试过的解决方法：
1. 去掉```document.documentElement.style.webkitUserSelect = "none";```
    actionSheet OK了，但是按住的div文字会被选中
2.  去掉div上的click或者tap事件
    某些情况下没问题，但是我需要点击事件，而且有时候还是会出现问题
3.  修改weui源码
``` javascript
     $actionSheetMask.addClass('weui-animate-fade-in').on('click', function () {
	        hide();
     });
```
把上面的click改成touchstart
    ok了，不过click和touchstart实际上还是有些不同的,而且电脑上又没有tochstart。。。

现在我完全理解不了iPhone同样的系统和微信，为什么会表现不一样

**Comment by yikuo123** [comment]
好像是松手的时候遮罩的click事件被触发了

**Comment by BearJ** [comment]
@yikuo123 有没有测试页面可以试试？在我这直接没响应taphold...根据描述可能是tap的穿透了而导致触发了mask的click事件。如果是这样的话， 你就需要在weui.actionSheet之后，remove掉$actionSheetMask的click事件。然后再自己绑定tap到mask上

**Comment by yikuo123** [comment]
问题应该是taphold触发了click事件，现在已经通过其它方式规避了。不过一直搞不懂为什么不是所有iphone都有这问题。

**Comment by yozman** [comment]
与 ionic 配合使用，(press) 绑定 actionSheet，会触发相同的问题
