### ISSUE TITLE
picker兼容性

### ISSUE THREAD

**Issue by stylejinmu** [weui/weui.js#74]
华为手机：android版本4.2.2，型号H30-U10。picker组件中，classs为weui-picker__indicator的下边框没显示。.weui-picker__indicator:after里的transform: scaleY(0.5)改为transform: scaleY(1)就显示了。但是这样的话边框粗了！
![wechatimg65](https://cloud.githubusercontent.com/assets/9429058/23657699/583f3964-037a-11e7-8062-addc367470c6.jpeg)

**Comment by BearJ** [comment]
@stylejinmu 老版本的机器分辨率不高的确会有这个问题，但因为其占有率，所以这里没做处理。如果您要处理的话，可以考虑变粗，毕竟兼容性是最好的。或者采用其它高分屏1像素线的实现方式：
![image](https://cloud.githubusercontent.com/assets/2395166/23844241/e022d82e-07fb-11e7-9a40-2b662a4f53c4.png)
