### ISSUE TITLE
form表单校验通过后样式不复原

### ISSUE THREAD

**Issue by wplin007** [weui/weui.js#75]
1、调用form的validate，没通过的input有警告样式、红色placeholder ，
2、再次校验，校验通过后的原来的警告样式并未消除造成困扰，不知道到底有没有通过（虽然我知道通过了，但页面还是警告状态）。
3、请问这个怎么处理？谢谢

**Comment by BearJ** [comment]
@wplin007 只需将`weui-cell`下的`weui-cell_warn`的扩展类移除即可。不过如果你有调用weui.form.checkIfBlur的话，当input聚焦的时候就会自动移除的。
