### ISSUE TITLE
weui有上拉加载数据，下拉刷新页面的功能吗？

### ISSUE THREAD

**Issue by LazyHua** [weui/weui.js#78]
要弄一个这样的上拉加载数据，下拉刷新页面的功能

**Comment by allan2coder** [comment]
没有

**Comment by yangkai314** [comment]
weui-react好像有这个功能

**Comment by xiaozhicode** [comment]
未来会增加这个功能吗？

**Comment by BearJ** [comment]
因为外部有很多类似组件，比如：https://www.boxfactura.com/pulltorefresh.js/
weui.js在这里就不重复造轮子了~~

**Comment by LazyHua** [comment]
@BearJ ，呜呜呜，好吧

**Comment by LazyHua** [comment]
@BearJ 加了pulltorefresh.js，然后现在有个小小的bug，就是，
![Uploading image.png…]()
instructionsPullToRefresh: 'Pull down to refresh',
  instructionsReleaseToRefresh: 'Release to refresh',
  instructionsRefreshing: 'Refreshing',
要怎么把这个文字修改为中文，插件好像不支持
