### ISSUE TITLE
picker 在三星曲面屏手机下严重错位

### ISSUE THREAD

**Issue by ringcrl** [weui/weui.js#82]
![fullsizerender](https://cloud.githubusercontent.com/assets/16740021/24068527/fc481c02-0bcb-11e7-8f4c-bdd667ba7a8d.jpg)

**Comment by sushuier** [comment]
给 body写  font-size:16px !important;

**Comment by ringcrl** [comment]
@sushuier 哈哈谢谢。看demo源码，里面好像说是weui的漏洞，不是weui.js的问题，需要fix一下

/* weui需要fix的 */

.weui-picker__item {
  padding: 0;
  height: 34px;
  line-height: 34px;
}

**Comment by sushuier** [comment]
我只记得 weui 的基准是  body font-size：16px；   所以 一旦 你的页面 body不是 16px  或者 html 写了 font-size:62.5%  就会出问题  尤其是在  ios下。
