### ISSUE TITLE
weui.confirm()回调无法出来weui.alert()

### ISSUE THREAD

**Issue by 270556660** [weui/weui.js#85]
weui.confirm()回调后再weui.alert()，weui.alert()无法出来代码如下
weui.confirm('自定义按钮的confirm', {
				title: '自定义按钮的confirm',
				buttons: [{
					label: 'NO',
					type: 'default'
				}, {
					label: 'YES',
					type: 'primary',
					onClick: function() {
						weui.alert('无法出来')
					}
				}]
			});

**Comment by progrape** [comment]
@270556660 请参考 #61
