### ISSUE TITLE
requirejs无法加载

### ISSUE THREAD

**Issue by hyingreborn** [weui/weui.js#9]
index.html 页面直接require(['weui'], function(weui)){ ... }
可以用...

index.html 页面中require a.js   a.js 依赖 weui.js，index.html页面会报错：
提示weui is not defined

**Comment by allan2coder** [comment]
建议修改下源码的外层，尝试下使用AMD的defined.

**Comment by progrape** [comment]
@hyingreborn @allan2coder 你好，编译输出是 webpack 以 UMD 的形式输出的

**Comment by wplin007** [comment]
在页面直接引用weui.js和css后
1、`weui.alert('test');`页面无反应。
2、通过按钮点击调用函数调用alert,弹出框出来了。
在weui.js  alert 函数中加的打印日志都执行了。不知道为什么。。。

**Comment by BearJ** [comment]
@wplin007 抱歉现在才看到：
