### ISSUE TITLE
datepicker兼容性问题

### ISSUE THREAD

**Issue by FiShelly** [weui/weui.js#94]
datepicker在iphone7 plus下会出现兼容性问题，导致无法正确选择日期。在iphone6下，调整了微信字体之后，在微信端浏览器访问页面，使用datepicker时，同样出现无法正确选择日期的情况。

**Comment by FiShelly** [comment]
![image](https://cloud.githubusercontent.com/assets/16427792/24784679/cf8cc454-1b86-11e7-8d19-1952f9bbdbf8.png)

**Comment by BearJ** [comment]
@FiShelly 看看这个是否能解决你的问题？#82

**Comment by FiShelly** [comment]
@BearJ 谢谢。
