### ISSUE TITLE
IOS10.3在微信下上传照片只能拍照不能选择文件？

### ISSUE THREAD

**Issue by Dean-Zhao** [weui/weui.js#98]
微信下ios10.3上传照片无法选择文件，去掉 capture 后仍旧不起作用
<input id="image" type="file" accept="image/*"/>

**Comment by Dean-Zhao** [comment]
<input id="uploaderInput" class="weui-uploader__input" type="file" accept="image/*"  multiple="multiple"> 在iOS9.3下可以同时打开相机和相册，但是在 iOS10.3 下 input就直接调用的相机；

**Comment by Dean-Zhao** [comment]
@BearJ 求大神帮忙看下

**Comment by merlinchen** [comment]
@Dean-Zhao 如果能提供一个可重现该问题的简单页面地址，会加快你的问题被定位和解决的速度，用plunker、codepen或其他均可。:D

**Comment by Dean-Zhao** [comment]
哈哈，我昨晚解决了，应该是缓存的问题，去掉capture 应该是起作用的，但是需要退出微信，重新登录，清掉缓存，就OK了；谢谢啦
